name: CMake_Ninja_ARM

on:
  push:
    branches: [ "master" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        cd project/ && rm -rf c_modules/ && /app/SimpleSourcePackageManager/cpacman/cpacman install && cd -
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -GNinja project/

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    - name: Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: binary_results
        path: |
          ${{github.workspace}}/build/bin/*.elf
          ${{github.workspace}}/build/bin/*.hex
          ${{github.workspace}}/build/bin/*.s19
          ${{github.workspace}}/build/bin/*.map

